# Programmare in Python

## Esercizi: Numpy

In questi esercizi array si riferisce a numpy.array


__1 - Create un array di 50 elementi, ciascuno uguale a $e$, la base dei logaritmi naturali. Verificate che l'array contenga esattamente 50 elementi.__ 

__2 - Create un array che contenga tutti gli angoli fra 0 e 360 gradi, in incrementi di un grado. Quanti sono gli elementi?__

__3 - Create un array di nove numeri equidistanti, il cui primo e ultimo elemento siano rispettivamente 0 e 23, e assegnarlo alla variabile r. Calcolate il quadrato di ciascun elemento di r. Calcolate il doppio di ogni elemento di r usando 1) moltiplicazione 2) somma.__ 

__4 - Create un array da 13 a 19, 19 escluso, in incrementi di 0.2__

__5 - Create un array da 13 a 19, 19 incluso, in incrementi di 0.2__

__6 - Create un array 5 × 5 che sia zero dappertutto ad eccezione della diagonale dove gli elementi sono [1,2,3,4,5]. Determinare size e shape dell'array.__

__7 - Create un array 8 × 8 con righe alternate di uno e zero.__

In [2]:
import numpy as np
A = np.zeros((8,8))
print(A)
print()
A[0:9:2,:]= 1 
A.astype('int')

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]



array([[1, 1, 1, 1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0, 0, 0, 0]])

__8 - Create un array 7 × 7 con colonne alternate di uno e zero.__

__9 - Dato l'array k = np.arange(2, 100, 3), aggiungete 100 a tutti i multipli di 7.__

In [3]:
k = np.arange(2, 100, 3)
print(k)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47 50 53 56 59 62 65 68 71
 74 77 80 83 86 89 92 95 98]


In [14]:
d=np.where(k%7==0)

In [24]:
k[d] = k[d]+100 

In [25]:
k

array([  2,   5,   8,  11, 114,  17,  20,  23,  26,  29,  32, 135,  38,
        41,  44,  47,  50,  53, 156,  59,  62,  65,  68,  71,  74, 177,
        80,  83,  86,  89,  92,  95, 198])

Altra soluzione:<BR>
np.where ha ulteriori possibilità:
np.where(condition,A,B) restituisce l'elemento di A se la condizione è verificata e l'elemento di B se non lo è.<BR>
e.g:

In [6]:
d = np.where(k%7==0,100+k,k)
d

array([  2,   5,   8,  11, 114,  17,  20,  23,  26,  29,  32, 135,  38,
        41,  44,  47,  50,  53, 156,  59,  62,  65,  68,  71,  74, 177,
        80,  83,  86,  89,  92,  95, 198])

__10 - Costruite la matrice:__
$$A = \begin{bmatrix} -2 & 3\\ 4 & 5 \end{bmatrix}$$
__Calcolate il determinante e, se possibile, l'inversa. Se l'inversa esiste controllate il vostro risultato calcolando il prodotto della matrice $A$ e della sua inversa.__

__11 - Risolvete il sistema di equazioni lineari:__
$$ 3 a + b - c = 1$$
$$ a - b + 2 c = 3$$
$$ -2 a + 3 b = 2$$ 

__12 - Scrivete una funzione che calcoli la distanza euclidea fra due punti in uno spazio ad N dimensioni, qualunque sia N.__

__13 - La posizione, al tempo t, di una palla che sia stata lasciata cadere con velocità iniziale nulla da una altezza h0 è data da:
$$y = h0 − \frac{1}{2}\, g\, t^2$$ 
dove $g = 9.81 m/s^2$. Supponiamo $h0 = 10\, m$. Trovate la sequenza di tempi a cui la palla completa ciascun intervallo di lunghezza mezzo metro, supponendo che la palla sia lasciata cadere a t=0. <br>
Suggerimento: create un array NumPy per y che va da 10 a 0 in incrementi di −0.5 usando la funzione arange.<br>
Salvate il vostro codice in una funzione. Una volta creati gli array y e t eseguite il comando `list(zip(t, y))`. Interpretate il risultato.__(D.J.Pine - Introduction to Python for Science and Engineering)

In [39]:
import numpy as np
y = np.arange(10.,-0.1,-0.5)
print(len(y))
y

21


array([10. ,  9.5,  9. ,  8.5,  8. ,  7.5,  7. ,  6.5,  6. ,  5.5,  5. ,
        4.5,  4. ,  3.5,  3. ,  2.5,  2. ,  1.5,  1. ,  0.5,  0. ])

$t = \sqrt{2 (h0 - y)/g}$

In [40]:
h0 = 10.
g = 9.81
t = np.sqrt(2.*(h0 - y)/g)
print(len(t))
t

21


array([0.        , 0.31927543, 0.45152364, 0.55300126, 0.63855086,
       0.71392156, 0.78206189, 0.84472338, 0.90304728, 0.95782629,
       1.00963755, 1.0589168 , 1.10600253, 1.15116393, 1.19461927,
       1.23654842, 1.27710171, 1.31640631, 1.35457092, 1.39168933,
       1.42784312])

In [41]:
list(zip(t,y))

[(0.0, 10.0),
 (0.3192754284070505, 9.5),
 (0.4515236409857309, 9.0),
 (0.553001263609331, 8.5),
 (0.638550856814101, 8.0),
 (0.7139215614635323, 7.5),
 (0.7820618870057751, 7.0),
 (0.8447233832986626, 6.5),
 (0.9030472819714618, 6.0),
 (0.9578262852211513, 5.5),
 (1.0096375546923044, 5.0),
 (1.0589168008061642, 4.5),
 (1.106002527218662, 4.0),
 (1.1511639281173525, 3.5),
 (1.194619265114655, 3.0),
 (1.2365484170737449, 2.5),
 (1.277101713628202, 2.0),
 (1.3164063149865983, 1.5),
 (1.3545709229571927, 1.0),
 (1.3916893275819882, 0.5),
 (1.4278431229270645, 0.0)]

In [42]:
def my_t_and_y(h0):
    g = 9.81
    y = np.arange(h0,-0.1,-0.5)
    t = np.sqrt(2.*(h0 - y)/g)
    return y,t

my_t_and_y(10.)

(array([10. ,  9.5,  9. ,  8.5,  8. ,  7.5,  7. ,  6.5,  6. ,  5.5,  5. ,
         4.5,  4. ,  3.5,  3. ,  2.5,  2. ,  1.5,  1. ,  0.5,  0. ]),
 array([0.        , 0.31927543, 0.45152364, 0.55300126, 0.63855086,
        0.71392156, 0.78206189, 0.84472338, 0.90304728, 0.95782629,
        1.00963755, 1.0589168 , 1.10600253, 1.15116393, 1.19461927,
        1.23654842, 1.27710171, 1.31640631, 1.35457092, 1.39168933,
        1.42784312]))

__14 - Ricordando che la velocità media su un intervallo $\Delta t$ è definita come $\bar{v} = \Delta y/\Delta t$, trovate la velocità media per ciascun intervallo del problema precedente utilizzando gli array NumPy.<br>
Suggerimento: cosa sono gli array y[1:21] e y[0:20]?.<br> 
Bonus 1: riuscite a immaginare un modo più elegante di rappresentare y[1:21]-y[0:20] che non fa riferimento esplicito al numero di elementi dell'array y, cioè che funzionerebbe per un array di lunghezza arbitraria?<br>
Bonus 2: Calcolate l'accelerazione in funzione del tempo usando la formula $\bar{a} = \Delta v/\Delta t$. Esprimete i tempi a cui le velocità sono calcolate prendendo il punto medio degli intervalli dell'array dei tempi usato in precedenza. Spiegate il risultato ottenuto per le accelerazioni.__(D.J.Pine - Introduction to Python for Science and Engineering)

In [32]:
print(y[20])
print(t[20])
print(y[1:21])
print(y[1:len(y)]) # more elegant way

0.0
1.4278431229270645
[9.5 9.  8.5 8.  7.5 7.  6.5 6.  5.5 5.  4.5 4.  3.5 3.  2.5 2.  1.5 1.
 0.5 0. ]
[9.5 9.  8.5 8.  7.5 7.  6.5 6.  5.5 5.  4.5 4.  3.5 3.  2.5 2.  1.5 1.
 0.5 0. ]


In [43]:
delta_y = y[1:21] - y[0:20]
print(len(delta_y))
delta_y

20


array([-0.5, -0.5, -0.5, -0.5, -0.5, -0.5, -0.5, -0.5, -0.5, -0.5, -0.5,
       -0.5, -0.5, -0.5, -0.5, -0.5, -0.5, -0.5, -0.5, -0.5])

In [44]:
delta_t = t[1:21] - t[0:20]
print(len(delta_t))
delta_t

20


array([0.31927543, 0.13224821, 0.10147762, 0.08554959, 0.0753707 ,
       0.06814033, 0.0626615 , 0.0583239 , 0.054779  , 0.05181127,
       0.04927925, 0.04708573, 0.0451614 , 0.04345534, 0.04192915,
       0.0405533 , 0.0393046 , 0.03816461, 0.0371184 , 0.0361538 ])

In [45]:
ave_v = delta_y/delta_t
print(len(ave_v))
ave_v

20


array([ -1.56604598,  -3.78076944,  -4.92719466,  -5.84456315,
        -6.63387721,  -7.33779881,  -7.97938175,  -8.57281511,
        -9.12758485,  -9.65041013, -10.14625911, -10.6189293 ,
       -11.07140146, -11.50606656, -11.92487748, -12.32945389,
       -12.72115688, -13.10114335, -13.47040653, -13.82980667])

In [36]:
t_mid = (t[0:20] + t[1:21])/2.
print(len(t_mid))
t_mid

20


array([0.15963771, 0.38539953, 0.50226245, 0.59577606, 0.67623621,
       0.74799172, 0.81339264, 0.87388533, 0.93043678, 0.98373192,
       1.03427718, 1.08245966, 1.12858323, 1.1728916 , 1.21558384,
       1.25682507, 1.29675401, 1.33548862, 1.37313013, 1.40976623])

Check:

In [25]:
i = 0
print(t[i],t[i+1],(t[i]+t[i+1])/2)

0.0 0.3192754284070505 0.15963771420352524


In [34]:
i = 19
print(t[i],t[i+1],(t[i]+t[i+1])/2)

1.3916893275819882 1.4278431229270645 1.4097662252545264


In [46]:
delta_ave_v = ave_v[1:20] - ave_v[0:19]
delta_delta_t = t_mid[1:20] - t_mid[0:19]
ave_a = delta_ave_v/delta_delta_t
ave_a

array([-9.81, -9.81, -9.81, -9.81, -9.81, -9.81, -9.81, -9.81, -9.81,
       -9.81, -9.81, -9.81, -9.81, -9.81, -9.81, -9.81, -9.81, -9.81,
       -9.81])