In [13]:
import numpy as np

arr = np.loadtxt( "/Users/maina/cernbox/python/MyCourse2/Data/test_2d.txt", skiprows=1)
print(arr)


[[ 0.  0.  1.  2.  3.]
 [10. 10. 11. 12. 13.]
 [20. 20. 21. 22. 23.]]


In [10]:
print(arr[1:,0])

[10. 20.]


In [11]:
print(arr[0,1:])

[0. 1. 2. 3.]


In [9]:
print(arr[1:,1:])

[[10. 11. 12. 13.]
 [20. 21. 22. 23.]]


In [15]:
xval=arr[1:,0]
yval=arr[0,1:]
print(xval.shape)

(2,)


strings, lists, ntuples, dictionaries
--------------------------------------

In [1]:
my_dict = {1:'a', 2:'b'}

In [2]:
1 in my_dict

True

In [4]:
3 in my_dict

False

In [3]:
'a' in my_dict.values()

True

In [5]:
'c' in my_dict.values()

False

In [6]:
my_tuple = (1,'b',[3,4])

In [7]:
1 in my_tuple

True

In [8]:
3 in my_tuple

False

In [10]:
[3,4] in my_tuple

True

In [12]:
a = tuple(range(2,7))
print(a)

(2, 3, 4, 5, 6)


In [13]:
b = a[::-1]
print(b)

(6, 5, 4, 3, 2)


In [14]:
help(str.replace)

Help on method_descriptor:

replace(self, old, new, count=-1, /)
    Return a copy with all occurrences of substring old replaced by new.
    
      count
        Maximum number of occurrences to replace.
        -1 (the default value) means replace all occurrences.
    
    If the optional argument count is given, only the first count occurrences are
    replaced.

